### PR TITLE
Change script path to be always absolute

### PR DESCRIPTION
**Pull request by akug**
With the new version, a specification.json that contains only the file name (as e.g. in examples/blast/specification.json, 0-start-log.sh) raises an error (b.c. at least in some shells, a file that should be executed always has to be a path like ./0-start-log.sh. This request changes all paths to absolute paths to avoid this problem.

### CODE REVIEW

**Comment by terrycojones** [comment]
Hi. What is the problem you are running into? Is it that some or all of the examples don't run for you due to the `./` issue?  This

> at least in some shells, a file that should be executed always has to be a path like ./0-start-log.sh

is a bit wrong. Both `0-start-log.sh` and `./0-start-log.sh` are relative paths and if your shell can't run the first one it's just because `.` is not in your `$PATH`. So more accurate is to say that a file that should be executed always has to be in your `$PATH`.

Anyway, I'll take a look at the diff.  It breaks many tests, because they don't know the absolute path of the scripts. See https://travis-ci.org/acorg/slurm-pipeline/jobs/370174991

At the very least the examples should be updated to use `./` in the script (or in your diff to use `.` if `cwd` is not given).

Thanks!

**Comment by terrycojones** [comment]
BTW, I'm wondering what the error you're seeing is because I'm not sure what you're trying to solve & the comment about the shell is confusing to me. `subprocess.check_output` doesn't use the shell to execute the command (unless you pass `shell=True`, which I don't).

**Comment by akug** [comment]
Hm I see. Sorry, I formulated this wrongly. 
So what I was trying to do is run your example in `slurm-pipeline/examples/blast` and it failed on my private machine (Ubuntu 17.10) and on a server running Debian 8. 
Adding a `./` before each script argument (`./0-start-log.sh`) solved this problem for me, but I could see other people running into this as well. Casting it to an absolute path seemed a good choice for me to avoid this problem completely. 
But if you rather suggest to add a `.` or a `./` depending on if `cwd` is given, i could also update the PR.

**Comment by terrycojones** [comment]
Hi - thanks, and no need to be sorry :-)  Are you running this on a UNIX machine, or Windows? It's really strange (if UNIX), because the shell (i.e., its PATH in this case) isn't used to find the executable. So a relative path (to a file that exists, of course) should always work. Putting `./` in front of it doesn't change anything, it's still just a relative path. But maybe you're on Windows....

**Comment by akug** [comment]
I agree that a relative path should work and I also agree that if `.` is in `$PATH`, the executable is found. However, this does not seem to be the standard for Ubuntu. So, if I am in a directory where the file `script.sh` is and I type just `script.sh` in my console, it gives me the error `command not found`, which is as you just explained because it searches only in my `$PATH` variable for a script with that name and not in `.` (as it is not included in `$PATH`). 
Do the examples still work for you? Do you have `.` in your `$PATH`? Otherwise I think I did not understand your explanation. 

But concluding, you are right that this problem can be simply solved by adding a `./` before each script name and then everything works as expected, so there is no real need for this PR.

**Comment by terrycojones** [comment]
I was able to reproduce this. I still find it a bit odd, but I think I understand what's going on. You'll only see this error if 1) There is no `/` in the path to your script (so `script.sh` may cause the problem, but `scripts/run.sh` will not, even though both are relative paths), and 2) if you do not have `.` in your `PATH`.  It seems that Python's `subprocess` module (actually `_posixsubprocess.fork_exec`) looks at your `PATH` if the first argument does not contain a `/`. If it does have one, like `scripts/run.sh` then it has no problem.  You can see this happening with a very simple example. Make a script called `run.sh` and try

```sh
$ python -c "import subprocess; subprocess.check_output(['run.sh'])"
$ python -c "import subprocess; subprocess.check_output(['./run.sh'])"
```

with and without `.` in your `PATH`.

I think this can be fixed by making an absolute path as you suggest, but that breaks about 15 tests (that check how the subprocess was called). I don't feel like dealing with this at the moment... But I have added a comment to the `script` documentation in the README and I have updated all the examples to use `./` when needed. So hopefully they will all run properly for everyone now.

Thanks for the report!  I'm not sure whether to just close this or to try to go down the `abspath` route and find a way to make the tests work (shouldn't be hard, just more manual in the call checking).

**Comment by terrycojones** [comment]
This was fixed (by using `./` before script names) so the examples will all run whether or not you have `.` in your `PATH` in https://github.com/acorg/slurm-pipeline/commit/6e035d6e8583293e3c18c964b171f629e5c8a434  Of course one is free to put absolute path names in for scripts in a specification file, but I don't want to do that in the examples because they need to run on other people's machines, not just mine.

Thanks for the pull request!

**Pull request closed without merging**
