### PR TITLE
adding installation instructions

### PR DESCRIPTION
**Pull request by ldynia**

### CODE REVIEW

**Comment by terrycojones** [comment]
Hi @ldynia - thanks for the pull request!  Can you change the bit in the install instructions to the following?

```sh
$ cd
$ git clone https://github.com/acorg/slurm-pipeline
$ cd slurm-pipeline
$ pip install -r requirements-2.txt
$ python setup.py install
```
and mention that one should use `requirements-3.txt` for Python 3?

The reason for removing the `which` command is that that is specific to some shells and, more important, the `/usr/local/bin/slurm-pipeline.py` output you show will likely be different for other people (including anyone using a Python virtual environment) so it might be confusing if people see a different result from `which`.

Have you been using the code?  Thanks again for bothering to send a pull request!

**Comment by ldynia** [comment]
Hi @terrycojones I have added requested changes. 

I would like to build a pipline(s) where each pipe is a independent micro-service build with docker (separation of concerns). Thus, I think that yours tool and others such as Luigi and NextFlow is a way to go. I want to compare them and see which one suits my needs.

P.S
Poll requests are cool! so it is a pleasure :)

**Comment by terrycojones** [comment]
Hi. Thanks - one more tiny thing, can you increment the version number in setup.py?  I could do it of course, but it's nice if it's all just your commit :-)

**Comment by ldynia** [comment]
@terrycojones done :)

**Comment by terrycojones** [comment]
Thanks!

**Pull request merged**
